### ISSUE TITLE
Custom 'referencedColumnName'

### ISSUE THREAD

**Issue by iBenito** [a2lix/I18nDoctrineBundle#22]
Some Translatable objects have a custom identifier. 

For example a Country table with "iso" as ID: 

```
    /**
     * @var string
     *
     * @ORM\Column(name="iso", type="string", length=2, nullable=false)
     * @ORM\Id
     */
    private $iso;
```

The DoctrineListener however, is hard-coding the 'referencedColumnName' to 'id'.

Is this something that will be supported?

**Comment by webda2l** [comment]
I close all issues and PRs.
This project is not maintained anymore. Prefer using https://github.com/KnpLabs/DoctrineBehaviors and re-use the Doctrine Filters feature.
