### ISSUE TITLE
get translations from entity

### ISSUE THREAD

**Issue by gfrancqu** [a2lix/I18nDoctrineBundle#24]
Hi,

I would like to now if there is a way to access different translations from the entity.

I have an entity TermeDico with a field "libelle" wich is being translated in french, spanish and english through a TermeDicoTranslation

all is working perfectly but I really need to get all the translations whatever the current locale.

the bundle just return the current translation.
I'm looking for a way to write getLibelleES, getLibelleEN and getLibelleFR methods.

Any solution would be welcome

**Comment by webda2l** [comment]
Hi,

This bundle allow use of @I18nDoctrine annotation (http://a2lix.fr/bundles/i18n-doctrine/#bundle-advanced).
What this annotation do, is disable the Doctrine filter https://github.com/a2lix/I18nDoctrineBundle/blob/master/Doctrine/ORM/EventListener/ControllerListener.php#L38.
Before any doctrine query, you can disable/enable this docrine filter.

**Comment by gfrancqu** [comment]
thanks for the answer, working perfectly

in order to use it with sonata i had to override the CRUDcontroller method in my termeDicoAdminController like this

```
/**
	 * @I18nDoctrine
	 */
	public function listAction() {
		return parent::listAction();
	}
```

now i can access every translation in my configureListFields function.

great work on this bundle, i tried lots of i18n bundle, and this one gave me entire satisfaction

**Comment by webda2l** [comment]
You're welcome, and glad you like this bundle.
