### ISSUE TITLE
Change folder of translation

### ISSUE THREAD

**Issue by abeloeil** [a2lix/I18nDoctrineBundle#26]
Hi!

Currently i have all my translations entity in the Entity folder, but i want to separate them like this:
- AcmeBundle
  - Entity
  - Translation
  - Repository

but i'm getting a MappingException:

> The target-entity AcmeBundle\Entity\ConfigTranslation cannot be found in  'AcmeBundle\Entity\Config#translations'.

Is that possible to do this?

Thanks!

**Comment by webda2l** [comment]
I close all issues and PRs.
This project is not maintained anymore. Prefer using https://github.com/KnpLabs/DoctrineBehaviors and re-use the Doctrine Filters feature.
