### ISSUE TITLE
Orphan removal

### ISSUE THREAD

**Issue by bsod85** [a2lix/I18nDoctrineBundle#30]
Hi!

Shouldn't the translations field mapping have the orphanRemoval option set to true?

I needed to remove a translation in a place where I don't have the entity manager service to call remove().

I think that adding the marked line inside A2lix/I18nDoctrineBundle/Doctrine/ORM/EventListener/DoctrineListener.php would best solve the problem for this use case.

```
// Translatable object?
if ($this->hasTrait($classMetadata->reflClass, $this->translatableTrait, $this->isRecursive)
                && !$classMetadata->hasAssociation('translations')) {
    $classMetadata->mapOneToMany(array(
        'fieldName' => 'translations',
       'mappedBy' => 'translatable',
        'fetch' => $this->translationFetchMode,
        'indexBy' => 'locale',
        'orphanRemoval' => true, <--------------- INSERTED CODE
        'cascade' => array('persist', 'merge', 'remove'),
        'targetEntity' => $classMetadata->name . 'Translation'
    ));
}
```

**Comment by webda2l** [comment]
I close all issues and PRs.
This project is not maintained anymore. Prefer using https://github.com/KnpLabs/DoctrineBehaviors and re-use the Doctrine Filters feature.
